# Amen
amen_styleguide_intro:
    path: /programmes/styleguide/amen
    defaults: { _controller: App\Controller\Styleguide\Amen\IntroController}

amen_styleguide_programmes:
    path: /programmes/styleguide/amen/domain/programme
    defaults: { _controller: App\Controller\Styleguide\Amen\Domain\ProgrammeController}

amen_styleguide_promotions:
    path: /programmes/styleguide/amen/domain/promotion
    defaults: { _controller: App\Controller\Styleguide\Amen\Domain\PromotionController}
