status:
    path: /status
    defaults: { _controller: AppBundle:Status:status }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /programmes
    defaults: { _controller: AppBundle:Home:show }
