parameters:
    guzzle.factory.group: 'aws'
    app.default_locale: 'en_GB'
    app.orbit_client.class: RMP\OrbClient\OrbitClient
    app.orbit_client.env: 'test'
    app.branding_client.class: BBC\BrandingClient\BrandingClient
    app.branding_client.env: 'test'

services:

    _defaults:
        autowire: true
        public: false

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']
            public: true  # Mandatory

        Twig_ExtensionInterface:
            tags: ['twig.extension']

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: ['kernel.event_subscriber']

        Symfony\Component\Form\FormTypeInterface:
            tags: ['form.type']

    AppBundle\:
        resource: '../../src/{Command,EventSubscriber,Twig}'

    AppBundle\Controller\:
        resource: '../../src/Controller'
        public: true # Mandatory
        tags: ['controller.service_arguments']


    ### Begin the services!

    # TODO: Work out how to pass through a SymfonyCache object wrapped in a
    # DoctrineProvider. So that we can see caching information in the profiler
    # panel that shall land in Symfony 3.3
    app.orbit_client:
        public: true
        class: '%app.orbit_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@doctrine_cache.providers.app_page_chrome'
            - { env: '%app.orbit_client.env%' }

    # TODO: Work out how to pass through a SymfonyCache object wrapped in a
    # DoctrineProvider. So that we can see caching information in the profiler
    # panel that shall land in Symfony 3.3
    app.branding_client:
        public: true
        class: '%app.branding_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@doctrine_cache.providers.app_page_chrome'
            - { env: '%app.branding_client.env%' }


    ### Translations

    RMP\Translate\TranslateFactory: ~

    app.translate_en:
        autowire: false
        class: RMP\Translate\Translate
        factory: ['@RMP\Translate\TranslateFactory', 'create']
        arguments: ['%app.default_locale%']


    ### Monitoring

    AppBundle\EventSubscriber\MonitoringSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
            - { name: 'monolog.logger', channel: 'app_access' }


    ### Programmes Service
    # TODO see if repeating every service here can be replaced with prototype
    # services in Symfony 3.3: https://github.com/symfony/symfony/pull/21289
    BBC\ProgrammesPagesService\Service\ServiceFactory: ~

    BBC\ProgrammesPagesService\Service\ProgrammesService:
        autowire: false
        factory: [ '@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getProgrammesService']
