parameters:
    app.default_locale: 'en_GB'
    app.orbit_client.class: BBC\BrandingClient\OrbitClient
    app.branding_client.class: BBC\BrandingClient\BrandingClient
    app.metric_cache.class: App\Metrics\Cache\MetricCacheApcu
    app.metric_backend.class: App\Metrics\Backend\CloudWatchMetricBackend
    frontend.aws.http_timeout: 15
    frontend.aws.http_connect_timeout: 5

services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # Autowire all necessary Twig, Argument resolver and Event Subscriber services
    App\:
        resource: '../../src/{ArgumentResolver,Branding,EventSubscriber,Twig}'

    # Autowire controllers in the DI layer and make them public
    App\Controller\:
        resource: '../../src/Controller'
        public: true # Mandatory


    ### Begin the services!

    App\Redis\RedisClusterFactory: ~

    App\Controller\ExceptionController:
        public: true
        arguments:
            $debug: '%kernel.debug%'

    ### Argument Value Resolvers

    App\ArgumentResolver\ContextEntityByPidValueResolver:
        tags: [{name: 'controller.argument_value_resolver', priority: 0 }]

    # This needs to be triggered before the RequestAttributeValueResolver,
    # which has a priority of 100
    App\ArgumentResolver\IdentifierValueResolver:
        tags: [{name: 'controller.argument_value_resolver', priority: 125 }]

    ### Caches

    cache.null_provider:
        class: Symfony\Component\Cache\Adapter\NullAdapter

    # we need an instance of RedisCluster, default Redis class doesn't support cluster mode.
    # RedisCluster class support most Redis operations
    cache.default_redis_provider:
        factory: 'App\Redis\RedisClusterFactory:createRedisCluster'
        class: App\Redis\RedisClusterFactory
        arguments:
            - ['%redis_endpoint%']
            - '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'cache' }

    ### Http Clients

    BBC\BrandingClient\OrbitClient:
        class: '%app.orbit_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@cache.programmes'
            - env: '%app.feed_env.orbit%'
              cacheKeyPrefix: 'frontend.%cosmos_component_release%.orbit'
              mustache: { cache: '%kernel.cache_dir%/mustache' }

    BBC\BrandingClient\BrandingClient:
        class: '%app.branding_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@cache.programmes'
            - env: '%app.feed_env.branding%'
              cacheKeyPrefix: 'frontend.%cosmos_component_release%.branding'

    ### Translations

    RMP\Translate\TranslateFactory:
        arguments:
            - fallback_locale: 'en_GB'
              cachepath: '%kernel.cache_dir%/translations'
              domains: ['programmes']
              default_domain: 'programmes'
              debug: '%kernel.debug%'
              basepath: '%kernel.project_dir%/app/Resources/translations'

    ### Monitoring

    App\EventSubscriber\MonitoringSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
            - { name: 'monolog.logger', channel: 'app_access' }

    App\Metrics\MetricsManager: ~

    App\Metrics\MetricsMiddleware:
        tags:
            - { name: 'csa_guzzle.middleware', alias: 'metrics_middleware', pritority: 90 }

    RMP\CloudwatchMonitoring\MonitoringHandler:
        arguments:
            $namespace: 'frontend'
            $env: '%cosmos_environment%'

    Aws\CloudWatch\CloudWatchClient:
        arguments:
            - region: '%aws_s3_region%'
              version: '2010-08-01'
              http:
                timeout: '%frontend.aws.http_timeout%'
                connect_timeout: '%frontend.aws.http_connect_timeout%'


    App\Metrics\Backend\MetricBackendInterface:
        class: '%app.metric_backend.class%'

    App\Metrics\Cache\MetricCacheInterface:
        class: "%app.metric_cache.class%"

    ### Programmes Service

    BBC\ProgrammesPagesService\Cache\CacheInterface:
        alias: BBC\ProgrammesPagesService\Cache\Cache

    BBC\ProgrammesPagesService\Cache\Cache:
        arguments: ['@cache.programmes', 'frontend.%cosmos_component_release%']

    BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\MapperFactory: ~

    BBC\ProgrammesPagesService\Service\ServiceFactory: ~

    BBC\ProgrammesPagesService\Service\BroadcastsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getBroadcastsService']

    BBC\ProgrammesPagesService\Service\CollapsedBroadcastsService:
            factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getCollapsedBroadcastsService']

    BBC\ProgrammesPagesService\Service\NetworksService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getNetworksService']

    BBC\ProgrammesPagesService\Service\ProgrammesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getProgrammesService']

    BBC\ProgrammesPagesService\Service\ServicesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getServicesService']
