# Amen
styleguide_intro:
    path: /programmes/styleguide/amen
    defaults: { _controller: App\Controller\Styleguide\Amen\IntroController}

styleguide_promotions:
    path: /programmes/styleguide/amen/promotion
    defaults: { _controller: App\Controller\Styleguide\Amen\PromotionController}
