monolog:
    handlers:
        cache:
            # We need to log warnings from the symfony cache layer, as these encompass important
            # redis errors, that are in no way warnings.
            type: fingers_crossed
            channels: ['cache']
            action_level: warning
            handler: nested
        main:
            # This handles logging everything else at $actionLevel (error),
            # according to the activation strategy in the service defined by HttpCodeActivationStrategy
            type: fingers_crossed
            activation_strategy: 'App\Exception\Handler\HttpCodeActivationStrategy'
            handler: nested
        nested:
            # And this is what kicks in once the activation strategy tells us we need to log
            type: stream
            path: '%kernel.logs_dir%/prod.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false


services:
    App\Exception\Handler\HttpCodeActivationStrategy:
        autowire: true
        arguments:
            $excludedCodes: [301, 302, 404]
            $actionLevel: error
