monolog:
    handlers:
        main:
            type: fingers_crossed
            channels: ['!app_access']
            activation_strategy: 'App\Exception\Handler\HttpCodeActivationStrategy'
            handler: nested
        app_access:
            type: stream
            channels: ['app_access']
            path: '%kernel.logs_dir%/prod-access.log'
            level: info
        nested:
            type: stream
            path: '%kernel.logs_dir%/prod.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false


services:
    App\Exception\Handler\HttpCodeActivationStrategy:
        autowire: true
        arguments:
            $excludedCodes: [301, 302, 404]
            $actionLevel: error
