parameters:
    app.feed_env.orbit: 'test'
    app.feed_env.branding: 'test'
    app.feed_env.morph.lxpromo: 'test'
    app.electron.baseurl: 'https://api.test.bbc.co.uk/electron'
    app.ada.baseurl: 'https://ada.test.api.bbci.co.uk'
    app.favourites.baseurl: 'https://www.test.bbc.co.uk/modules/plugin/musicfavourite/init'
    app.recipes.baseurl: 'https://api.test.bbc.co.uk/food/recipes'
    app.morph.baseurl: 'https://morph.test.api.bbci.co.uk'
